nodes:
  - name: wazuh-indexer
    type: indexer
    ip: wazuh-indexer

  - name: wazuh-manager
    type: server
    ip: wazuh-manager

  - name: wazuh-dashboard
    type: dashboard
    ip: wazuh-dashboard

output_dir: /certificates